### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by marzzzello** [ankicommunity/anki-sync-server-rs#8]
I tried to change the sync server from the Python server to this sync server with Anki desktop 2.1.49.
I changed the URL in the add-on to the new server and ran sync. Both normal and force sync produced an error.

ankisyncd 0.1.2 (latest master) in Docker container behind reverse proxy (local server produces same error)
RUST_BACKTRACE enabled
Default config, I just added one user

Normal sync:
```
[2021-12-11T19:43:04Z INFO  actix_server::builder] Starting 2 workers
[2021-12-11T19:43:04Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:27701" service on 0.0.0.0:27701
thread 'actix-rt:worker:0' panicked at 'called `Option::unwrap()` on a `None` value', src/sync.rs:388:38
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: ankisyncd::sync::sync_app::{{closure}}
   4: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
   5: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   6: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
  10: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  11: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
  12: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::handle_request
  13: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_request
  14: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
  15: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  18: std::panicking::try
  19: tokio::runtime::task::harness::Harness<T,S>::poll
  20: std::thread::local::LocalKey<T>::with
  21: tokio::task::local::LocalSet::tick
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: tokio::macros::scoped_tls::ScopedKey<T>::set
  25: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  26: tokio::runtime::handle::Handle::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'actix-rt:worker:1' panicked at 'called `Option::unwrap()` on a `None` value', src/sync.rs:278:20
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: ankisyncd::sync::add_col
   4: ankisyncd::sync::sync_app::{{closure}}
   5: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
   6: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
  10: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  11: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
  12: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
  13: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
  14: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: std::panicking::try
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: std::thread::local::LocalKey<T>::with
  20: tokio::task::local::LocalSet::tick
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
  24: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  25: tokio::runtime::handle::Handle::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

With force sync in one direction enabled:
```
thread 'actix-rt:worker:0' panicked at 'called `Option::unwrap()` on a `None` value', src/sync.rs:278:20
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: ankisyncd::sync::add_col
   4: ankisyncd::sync::sync_app::{{closure}}
   5: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
   6: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
  10: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  11: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
  12: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
  13: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
  14: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: std::panicking::try
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: std::thread::local::LocalKey<T>::with
  20: tokio::task::local::LocalSet::tick
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
  24: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  25: tokio::runtime::handle::Handle::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'actix-rt:worker:1' panicked at 'called `Option::unwrap()` on a `None` value', src/sync.rs:388:38
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: ankisyncd::sync::sync_app::{{closure}}
   4: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
   5: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   6: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
  10: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  11: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
  12: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::handle_request
  13: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_request
  14: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
  15: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  18: std::panicking::try
  19: tokio::runtime::task::harness::Harness<T,S>::poll
  20: std::thread::local::LocalKey<T>::with
  21: tokio::task::local::LocalSet::tick
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: tokio::macros::scoped_tls::ScopedKey<T>::set
  25: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  26: tokio::runtime::handle::Handle::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dobefore** [comment]
it seems you have anki being logged in before switching to this server and don't log out,is it the truth? you should log out and login with new user.

>  I changed the URL in the add-on to the new server and

are you using address 0.0.0.0:27701 in anki addon?That address means Server will listen to client not limited to local host.this is unnecessary.you can configure this as usual.

if this is not a fix,feel free to add

**Comment by marzzzello** [comment]
Thanks for your help.
Yes, I didn't log out and in. Now when I try to login I get this error:
```
Authentication succeeded for  user marzzzello.
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/session.rs:73:47
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at ./rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: ankisyncd::session::Session::new
   4: ankisyncd::sync::sync_app::{{closure}}
   5: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
   6: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
  10: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  11: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
  12: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
  13: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
  14: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: std::panicking::try
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: std::thread::local::LocalKey<T>::with
  20: tokio::task::local::LocalSet::tick
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
  24: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  25: tokio::runtime::handle::Handle::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dobefore** [comment]
this is a bug on my side,apologize.a fix is done.please pull and rebuild:)

**Comment by marzzzello** [comment]
Thank you, it syncs now :smile_cat:
